package com.arquisoft.notificaciones.infrastructure.notificacion.command.primaryadapter.amqp;

import lombok.Getter;

@Getter
public enum TipoNotificacionEvento {

    ASESOR_FICHA_CAMBIADO("ASESOR_FICHA_CAMBIADO"),
    FICHA_PERFIL_REGISTRADA_ASESOR("FICHA_PERFIL_REGISTRADA_ASESOR"),
    ESTUDIANTES_FICHA_PERFIL_ASIGNADOS("ESTUDIANTES_FICHA_PERFIL_ASIGNADOS"),
    SOLICITUD_NOVEDAD_COORDINADOR("SOLICITUD_NOVEDAD_COORDINADOR"),
    SOLICITUD_NOVEDAD_COORDINADOR_RESPONDIDA("SOLICITUD_NOVEDAD_COORDINADOR_RESPONDIDA"),
    SOLICITUD_NOVEDAD_COORDINADOR_ESTADO_MODIFICADO("SOLICITUD_NOVEDAD_COORDINADOR_ESTADO_MODIFICADO"),
    SOLICITUD_NOVEDAD_ASESOR_ESTADO_MODIFICADO("SOLICITUD_NOVEDAD_ASESOR_ESTADO_MODIFICADO"),
    SOLICITUD_NOVEDAD_ASESOR("SOLICITUD_NOVEDAD_ASESOR"),
    SOLICITUD_NOVEDAD_ASESOR_RESPONDIDA("SOLICITUD_NOVEDAD_ASESOR_RESPONDIDA"),
    SOLICITUD_CAMBIO_ASESOR("SOLICITUD_CAMBIO_ASESOR"),
    SOLICITUD_AMPLIACION_PLAZO("SOLICITUD_AMPLIACION_PLAZO"),
    REVISION_ITEM_AGREGADO("REVISION_ITEM_AGREGADO"),
    USUARIO_ESTADO_CAMBIADO("USUARIO_ESTADO_CAMBIADO"),
    FICHA_PERFIL_APROBADA_ESTUDIANTE("FICHA_PERFIL_APROBADA_ESTUDIANTE"),
    FICHA_PERFIL_APROBADA_ASESOR("FICHA_PERFIL_APROBADA_ASESOR"),
    FICHA_PERFIL_NO_APROBADA_ESTUDIANTE("FICHA_PERFIL_NO_APROBADA_ESTUDIANTE"),
    FICHA_PERFIL_NO_APROBADA_ASESOR("FICHA_PERFIL_NO_APROBADA_ASESOR"),
    PROYECTO_GRADO_REGISTRADO_COORDINADOR("PROYECTO_GRADO_REGISTRADO_COORDINADOR"),
    ESTUDIANTES_PROYECTO_GRADO_ASIGNADOS("ESTUDIANTES_PROYECTO_GRADO_ASIGNADOS"),
    ESTADO_FICHA_PERFIL_AGREGADO("ESTADO_FICHA_PERFIL_AGREGADO");

    private final String codigo;

    TipoNotificacionEvento(String codigo) {
        this.codigo = codigo;
    }

}
