dependencies {
    implementation project(':shared:domain')
    implementation project(':shared:exceptions')
    
    // Spring Web
    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    
    // REST Client
    implementation "org.springframework.boot:spring-boot-starter-webflux:${springBootVersion}"
    
    // JSON processing
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    
    // Validation
    implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
}
