dependencies {
    implementation project(':shared:domain')
    implementation project(':shared:exceptions')
    
    // Spring Validation
    implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
    
    // Jakarta Bean Validation
    implementation "jakarta.validation:jakarta.validation-api:3.1.1"
    implementation "org.hibernate.validator:hibernate-validator:8.0.1.Final"
}
